name: Deploy (Build && Push)
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: |
          docker login \
                 -u "${{ secrets.DOCKERHUB_USERNAME }}" \
                 -p "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Build && Push
        run: ./deploy.sh 8 egison/egison
