name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker build -t egison/egison:latest .
    - run: docker run --rm -i egison/egison:latest -v
